# Generated by Django 5.0.7 on 2024-09-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_groupchat_alter_photosubmission_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
