# Generated by Django 5.0.7 on 2024-10-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_member_is_admin_alter_groupchat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='points_adjustment',
            field=models.FloatField(default=0),
        ),
    ]
