# Generated by Django 5.0.7 on 2024-10-19 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_event_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='photosubmission',
            name='description',
            field=models.TextField(blank=True, choices=[('random', 'On-campus random encounter'), ('fun', 'On-campus fun event'), ('single', 'Off-campus single fam event'), ('crossover', 'Off-campus crossover fam event'), ('ssa', 'SSA-wide event')]),
        ),
        migrations.AlterField(
            model_name='photosubmission',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_submissions', to='backend.member'),
        ),
        migrations.AlterField(
            model_name='photosubmission',
            name='score',
            field=models.FloatField(blank=True, verbose_name='Score (leave blank to auto-calculate)'),
        ),
    ]
