# Generated by Django 5.0.7 on 2024-10-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_member_image_remove_member_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosubmission',
            name='vetted',
            field=models.BooleanField(default=False),
        ),
    ]
