# Generated by Django 5.0.7 on 2024-10-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_photosubmission_vetted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosubmission',
            name='score',
            field=models.FloatField(blank=True, verbose_name='Score (delete to auto-calculate)'),
        ),
    ]
