# Generated by Django 5.1.2 on 2024-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_photosubmission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image_folder_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
