# Generated by Django 5.1.2 on 2025-01-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_event_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcoMember',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('photo_id', models.CharField(blank=True, null=True)),
                ('alt_photo_id', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
