# Generated by Django 5.1.2 on 2025-01-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_excomember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excomember',
            name='major',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='excomember',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='excomember',
            name='role',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='excomember',
            name='year',
            field=models.CharField(),
        ),
    ]
