# Generated by Django 5.0.1 on 2024-04-04 18:16

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_member_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=backend.models.ModifiedGoogleDriveStorage(), upload_to='event_images'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=backend.models.ModifiedGoogleDriveStorage(), upload_to='profile_images'),
        ),
    ]
