# Generated by Django 5.0.1 on 2024-04-04 18:16

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_member_family'),
    ]

    operations = [
    ]
