# Generated by Django 5.0.1 on 2024-04-05 08:25

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_event_image_url_member_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image url (do not edit)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Profile image url (do not edit)'),
        ),
    ]
