# Generated by Django 5.0.1 on 2024-07-14 14:24

import backend.models
import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_profile_image_member_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=backend.models._get_upload_path),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=backend.models._get_upload_path),
        ),
        migrations.AlterField(
            model_name='member',
            name='image_id',
            field=models.CharField(blank=True, null=True, verbose_name='Image id (do not edit)'),
        ),
    ]
