# Generated by Django 5.0.1 on 2024-07-15 21:32

import backend.models
import django.db.models.deletion
import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('backend', '0013_member_telegram_username'), ('backend', '0014_alter_member_telegram_username'), ('backend', '0015_photosubmission'), ('backend', '0016_member_telegram_id'), ('backend', '0017_alter_member_telegram_id'), ('backend', '0018_alter_family_points')]

    dependencies = [
        ('backend', '0012_alter_event_image_alter_member_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PhotoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(blank=True, null=True, verbose_name='Image id (do not edit)')),
                ('image', models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=backend.models._get_upload_path)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('number_of_people', models.IntegerField(default=0)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_submissions', to='backend.family')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_submissions', to='backend.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='member',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
