# Generated by Django 5.0.1 on 2024-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_event_image_alter_member_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
