# Generated by Django 5.0.1 on 2024-07-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_member_telegram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
