# Generated by Django 5.0.1 on 2024-07-15 13:03

import backend.models
import django.db.models.deletion
import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_member_telegram_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(blank=True, null=True, verbose_name='Image id (do not edit)')),
                ('image', models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=backend.models._get_upload_path)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('number_of_people', models.IntegerField(default=0)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_submissions', to='backend.family')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_submissions', to='backend.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
