# Generated by Django 5.0.1 on 2024-07-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_photosubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
