# Generated by Django 5.0.1 on 2024-07-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_member_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
