# Generated by Django 5.0.1 on 2024-07-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_member_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
