# Generated by Django 5.0.1 on 2024-07-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_event_image_alter_member_image_and_more_squashed_0018_alter_family_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='points',
        ),
    ]
